#!/usr/bin/env bash
# A script that gives you information about the school file

if [ -e "school" ]
then
	echo "school file exist"
	if [ -s "school" ]
	then
		echo "school is not empty"
	else
		echo "school is empty"
	fi

	if [ -f "school" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
